version: '3'

services:

    kru-postgres:
        image: postgres:11
        restart: always

        ports:
            - ${DATABASE_PORT}:5432
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASS}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_DB}

    kru-redis:
        image: 'redis:4-alpine'
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - '${REDIS_PORT}:6379'

    kru-minio:
        hostname: kru-minio
        image: minio/minio:RELEASE.2021-09-18T18-09-59Z
        container_name: kru-minio

        volumes:
            - './kru/data/:/data'
            - './kru/config:/root/.minio'

        ports:
            - ${MINIO_PORT}:9000
            - ${MINIO_PORT_2}:9001
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        command: server --console-address ":9001"  /data

    kru-createbuckets:
        image: minio/mc
        depends_on:
            - kru-minio
        entrypoint: >
            /bin/sh -c " sleep 10; /usr/bin/mc config host add data http://${BUCKET_MINIO_HOST}:${BUCKET_MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}; /usr/bin/mc mb data/${MINIO_BUCKET}; /usr/bin/mc policy set public data/${MINIO_BUCKET}; exit 0; "
    
    kru-imgproxy:
        image: 'darthsim/imgproxy:latest'
        ports:
            - '${IMGPROXY_PORT}:8080'
        depends_on:
            - kru-minio
        links:
            - kru-minio
        environment:
            IMGPROXY_KEY: ${IMGPROXY_KEY}
            IMGPROXY_SALT: ${IMGPROXY_SALT}
            IMGPROXY_MAX_SRC_FILE_SIZE: 10485760
