export const TALENTS_INFO_REPOSITORY = Symbol('TALENTS_INFO_REPOSITORY');
export const TALENTS_SKILLS_REPOSITORY = Symbol('TALENTS_SKILLS_REPOSITORY');

export const TALENTS_INFO_SERVICE = Symbol('TALENTS_INFO_SERVICE');

export const TALENTS_EDUCATION_REPOSITORY = Symbol('TALENTS_EDUCATION_REPOSITORY');

export const TALENT_LIKE_REPOSITORY = Symbol('TALENT_LIKE_REPOSITORY');
