export const PASSWORD_HASH_SALT = Symbol('PASSWORD_HASH_SALT');

export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const USERS_SOCIALS_REPOSITORY = Symbol('USERS_SOCIALS_REPOSITORY');

export const USERS_SERVICE = Symbol('USERS_SERVICE');

export const USERS_ACTIVATED_CODE_REPOSITORY = Symbol('USERS_ACTIVATED_CODE_REPOSITORY');
export const USERS_ACTIVATED_CODE_SERVICE = Symbol('USERS_ACTIVATED_CODE_SERVICE');

export const USERS_USED_CODES_REPOSITORY = Symbol('USERS_USED_CODES_REPOSITORY');
