export const NOTIFICATIONS_REPOSITORY = Symbol('NOTIFICATIONS_REPOSITORY');
export const NOTIFICATIONS_USERS_DEVICES_REPOSITORY = Symbol(
	'NOTIFICATIONS_USERS_DEVICES_REPOSITORY',
);
export const NOTIFICATIONS_SETTINGS_REPOSITORY = Symbol('NOTIFICATIONS_SETTINGS_REPOSITORY');

export const NOTIFICATIONS_SERVICE = Symbol('NOTIFICATIONS_SERVICE');
