export const JOB_REPOSITORY = Symbol('JOB_REPOSITORY');
export const JOB_SERVICES = Symbol('JOB_SERVICES');

export const JOB_APPEARANCE_REPOSITORY = Symbol('JOB_APPEARANCE_REPOSITORY');
export const JOB_APPEARANCE_SERVICES = Symbol('JOB_APPEARANCE_SERVICES');

export const JOB_MEASUREMENT_REPOSITORY = Symbol('JOB_MEASUREMENT_REPOSITORY');
export const JOB_MEASUREMENT_SERVICES = Symbol('JOB_MEASUREMENT_SERVICES');

export const JOB_TO_TAG_REPOSITORY = Symbol('JOB_TO_TAG_REPOSITORY');

export const JOB_RESIDENCE_REPOSITORY = Symbol('JOB_RESIDENCE_REPOSITORY');
