import { TagCategory } from '../enums';

export const JOB_TYPE_PROJECT = [
	{
		name: 'Feature films',
		key: 'featureFilms',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Documentary films',
		key: 'documentaryFilms',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Short films',
		key: 'shortFilms',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'TV shows',
		key: 'tvShows',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Web series',
		key: 'webSeries',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Commercials',
		key: 'commercials',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Music videos',
		key: 'musicVideos',
		category: TagCategory.JobTypeProject,
		parentKey: 'filmProject',
	},
	{
		name: 'Albums',
		key: 'albums',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'Singles',
		key: 'singles',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'EPs',
		key: 'eps',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'Music videos',
		key: 'musicVideos',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'Concerts and tours',
		key: 'concertsAndTours',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'Soundtracks',
		key: 'soundtracks',
		category: TagCategory.JobTypeProject,
		parentKey: 'music',
	},
	{
		name: 'TV series',
		key: 'tvSeries',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'Miniseries',
		key: 'miniseries',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'Made-for-TV movies',
		key: 'madeForTv',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'Reality TV shows',
		key: 'realityTvShows',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'News programs',
		key: 'newsPrograms',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'Sports broadcasts',
		key: 'sportsBroadcasts',
		category: TagCategory.JobTypeProject,
		parentKey: 'televisionProject',
	},
	{
		name: 'PC games',
		key: 'pcGames',
		category: TagCategory.JobTypeProject,
		parentKey: 'videoGame',
	},
	{
		name: 'Mobile games',
		key: 'mobileGames',
		category: TagCategory.JobTypeProject,
		parentKey: 'videoGame',
	},
	{
		name: 'Virtual reality games',
		key: 'virtualRealityGames',
		category: TagCategory.JobTypeProject,
		parentKey: 'videoGame',
	},
	{
		name: 'Console games',
		key: 'consoleGames',
		category: TagCategory.JobTypeProject,
		parentKey: 'videoGame',
	},
	{
		name: 'Concerts',
		key: 'concerts',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Theater productions',
		key: 'theaterProductions',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Dance performances',
		key: 'dancePerformances',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Comedy shows',
		key: 'comedyShows',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Magic shows',
		key: 'magicShows',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Circus performances',
		key: 'circusPerformances',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Sporting events',
		key: 'sportingEvents',
		category: TagCategory.JobTypeProject,
		parentKey: 'liveEntertainment',
	},
	{
		name: 'Books',
		key: 'books',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'Magazines',
		key: 'magazines',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'Newspapers',
		key: 'newspapers',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'Comics and graphic novels',
		key: 'comicsAndGraphicNovels',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'E-books',
		key: 'eBooks',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'Audiobooks',
		key: 'audiobooks',
		category: TagCategory.JobTypeProject,
		parentKey: 'publishing',
	},
	{
		name: 'Representing actors',
		key: 'representingActors',
		category: TagCategory.JobTypeProject,
		parentKey: 'talentAgency',
	},
	{
		name: 'Representing musicians',
		key: 'representingMusicians',
		category: TagCategory.JobTypeProject,
		parentKey: 'talentAgency',
	},
	{
		name: 'Representing directors and producers',
		key: 'representingDirectorsAndProducers',
		category: TagCategory.JobTypeProject,
		parentKey: 'talentAgency',
	},
	{
		name: 'Negotiating contracts',
		key: 'negotiatingContracts',
		category: TagCategory.JobTypeProject,
		parentKey: 'talentAgency',
	},
	{
		name: 'Advising clients on career move',
		key: 'advisingClientsOnCareerMove',
		category: TagCategory.JobTypeProject,
		parentKey: 'talentAgency',
	},
	{
		name: 'Community management',
		key: 'communityManagement',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Analytics and insights',
		key: 'analyticsAndInsights',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Advertising production',
		key: 'advertisingProduction',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Influencer production',
		key: 'influencerProduction',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Strategy development',
		key: 'strategyDevelopment',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Collaboration',
		key: 'collaboration',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
	{
		name: 'Content production',
		key: 'contentProduction',
		category: TagCategory.JobTypeProject,
		parentKey: 'socialMediaProject',
	},
];
