import { TagCategory } from '../enums';

export const JOB_TYPE_JOBS = [
	{
		name: 'Production',
		key: 'production',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Direction',
		key: 'direction',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Writing',
		key: 'writing',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Art Department',
		key: 'artDepartment',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Locations',
		key: 'locations',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Camera and Cinematography',
		key: 'cameraAndCinematography',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Lighting and Grip',
		key: 'lightingAndGrip',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Sound',
		key: 'sound',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Music',
		key: 'musicJob',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Casting',
		key: 'casting',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Stunts',
		key: 'stunts',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Costumes and Makeup',
		key: 'costumesAndMakeup',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Special Effects',
		key: 'specialEffects',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Post-Production',
		key: 'postProduction',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Marketing and Distribution',
		key: 'marketingAndDistribution',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},
	{
		name: 'Film Preservation and History',
		key: 'filmPreservationAndHistory',
		category: TagCategory.JobTypeJobs,
		parentKey: 'film',
	},

	{
		name: 'Production',
		key: 'productionTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Direction',
		key: 'directionTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Writing',
		key: 'writingTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Art Department',
		key: 'artDepartmentTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Locations',
		key: 'locationsTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Camera and Cinematography',
		key: 'cameraAndCinematographyTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Lighting and Grip',
		key: 'lightingAndGripTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Sound',
		key: 'soundTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Music',
		key: 'musicJobTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Casting',
		key: 'castingTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Stunts',
		key: 'stuntsTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Costumes and Makeup',
		key: 'costumesAndMakeupTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Special Effects',
		key: 'specialEffectsTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Post-Production',
		key: 'postProductionTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'televisionTelevision',
	},
	{
		name: 'Marketing and Distribution',
		key: 'marketingAndDistributionTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
	{
		name: 'Film Preservation and History',
		key: 'filmPreservationAndHistoryTelevision',
		category: TagCategory.JobTypeJobs,
		parentKey: 'television',
	},
];
