import { TagCategory } from '../enums';

export const JOB = [
	{
		name: 'Social media manager',
		key: 'socialMediaManager',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Web developer',
		key: 'webDeveloper',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media strategist',
		key: 'socialMediaStrategist',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Content creator',
		key: 'contentCreator',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Influencer',
		key: 'influencer',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Community manager',
		key: 'communityManager',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media advertising specialist',
		key: 'socialMediaAdvertisingSpecialist',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Data analyst',
		key: 'dataAnalyst',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'SEO specialist',
		key: 'SEO',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Public relations specialist',
		key: 'publicRelationsSpecialist',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Customer service representative',
		key: 'customerServiceRepresentative',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Graphic designer',
		key: 'graphicDesigner',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Video editor',
		key: 'videoEditor',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Copywriter',
		key: 'copywriter',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Brand manager',
		key: 'Brand manager',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Project manager',
		key: 'projectManager',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Digital marketing specialist',
		key: 'digitalMarketingSpecialist',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media coordinator',
		key: 'socialMediaCoordinator',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media consultant',
		key: 'socialMediaConsultant',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media trainer or coach',
		key: 'socialMediaTrainerOrCoach',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Account executive',
		key: 'accountExecutive',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Social media intern',
		key: 'socialMediaIntern',
		parentKey: 'socialMedia',
		category: TagCategory.Job,
	},
	{
		name: 'Producer',
		key: 'producer',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Executive',
		key: 'executive',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Producer',
		key: 'producer',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Line Producer',
		key: 'lineProducer',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Co-Producer',
		key: 'coProducer',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Associate Producer',
		key: 'associateProducer',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Unit Production Manager',
		key: 'unitProductionManager',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Production Coordinator',
		key: 'productionCoordinator',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Production Secretary',
		key: 'productionSecretary',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Production Assistant',
		key: 'productionAssistant',
		parentKey: 'production',
		category: TagCategory.Job,
	},
	{
		name: 'Director',
		key: 'director',
		parentKey: 'direction',
		category: TagCategory.Job,
	},
	{
		name: 'Assistant Director',
		key: 'assistantDirector',
		parentKey: 'direction',
		category: TagCategory.Job,
	},
	{
		name: 'Second Assistant Director',
		key: 'secondAssistantDirector',
		parentKey: 'direction',
		category: TagCategory.Job,
	},
	{
		name: 'Screenwriter',
		key: 'screenwriter',
		parentKey: 'writing',
		category: TagCategory.Job,
	},
	{
		name: 'Story Editor',
		key: 'storyEditor',
		parentKey: 'writing',
		category: TagCategory.Job,
	},
	{
		name: 'Production Designer',
		key: 'productionDesigner',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Art Director',
		key: 'artDirector',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Set Decorator',
		key: 'setDecorator',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Set Designer',
		key: 'setDesigner',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Prop Master',
		key: 'propMaster',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Construction Coordinator',
		key: 'constructionCoordinator',
		parentKey: 'artDepartment',
		category: TagCategory.Job,
	},
	{
		name: 'Location Manager',
		key: 'locationManager',
		parentKey: 'locations',
		category: TagCategory.Job,
	},
	{
		name: 'Location Scout',
		key: 'locationScout',
		parentKey: 'locations',
		category: TagCategory.Job,
	},
	{
		name: 'Cinematographer/Director of Photography',
		key: 'cDirectorOfPhotography',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Camera Operator',
		key: 'cameraOperator',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Steadicam Operator',
		key: 'steadicamOperator',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Focus Puller/1st Assistant Camera',
		key: 'focusPuller/1stAssistantCamera',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Clapper Loader/2nd Assistant Camera',
		key: 'clapperLoader/2ndAssistantCamera',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Digital Imaging Technician',
		key: 'digitalImagingTechnician',
		parentKey: 'cameraAndCinematography',
		category: TagCategory.Job,
	},
	{
		name: 'Gaffer',
		key: 'gaffer',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Best Boy Electric',
		key: 'bestBoyElectric',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Electrician',
		key: 'electrician',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Key Grip',
		key: 'keyGrip',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Best Boy Grip',
		key: 'bestBoyGrip',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Grip',
		key: 'grip',
		parentKey: 'lightingAndGrip',
		category: TagCategory.Job,
	},
	{
		name: 'Sound Designer',
		key: 'soundDesigner',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'Sound Mixer',
		key: 'soundMixer',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'Boom Operator',
		key: 'boomOperator',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'Foley Artist',
		key: 'foleyArtist',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'ADR Editor',
		key: 'adr',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'Dialogue Editor',
		key: 'dialogueEditor',
		parentKey: 'sound',
		category: TagCategory.Job,
	},
	{
		name: 'Composer',
		key: 'composer',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Supervisor',
		key: 'musicSupervisor',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Editor',
		key: 'musicEditor',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Musician',
		key: 'musician',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Arranger',
		key: 'musicArranger',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Producer',
		key: 'musicProducer',
		parentKey: 'musicJob',
		category: TagCategory.Job,
	},
	{
		name: 'Casting Director',
		key: 'castingDirector',
		parentKey: 'casting',
		category: TagCategory.Job,
	},
	{
		name: 'Talent Agent',
		key: 'talentAgent',
		parentKey: 'casting',
		category: TagCategory.Job,
	},
	{
		name: 'Actor',
		key: 'actor',
		parentKey: 'casting',
		category: TagCategory.Job,
	},
	{
		name: 'Extras',
		key: 'extras',
		parentKey: 'casting',
		category: TagCategory.Job,
	},
	{
		name: 'Stunt Coordinator',
		key: 'stuntCoordinator',
		parentKey: 'stunts',
		category: TagCategory.Job,
	},
	{
		name: 'Stunt Performer',
		key: 'stuntPerformer',
		parentKey: 'stunts',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Designer',
		key: 'costumeDesigner',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Supervisor',
		key: 'costumeSupervisor',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Assistant',
		key: 'costumeAssistant',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Wardrobe Master',
		key: 'wardrobeMaster',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Makeup Artist',
		key: 'makeupArtist',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Hair Stylist',
		key: 'hairStylist',
		parentKey: 'costumesAndMakeup',
		category: TagCategory.Job,
	},
	{
		name: 'Special Effects Technician',
		key: 'specialEffectsTechnician',
		parentKey: 'specialEffects',
		category: TagCategory.Job,
	},
	{
		name: 'Special Effects Supervisor',
		key: 'specialEffectsSupervisor',
		parentKey: 'specialEffects',
		category: TagCategory.Job,
	},
	{
		name: 'Visual Effects Supervisor',
		key: 'visualEffectsSupervisor',
		parentKey: 'specialEffects',
		category: TagCategory.Job,
	},
	{
		name: 'Visual Effects Artist',
		key: 'visualEffectsArtist',
		parentKey: 'specialEffects',
		category: TagCategory.Job,
	},
	{
		name: 'Editor',
		key: 'editor',
		parentKey: 'postProduction',
		category: TagCategory.Job,
	},
	{
		name: 'Assistant Editor',
		key: 'assistantEditor',
		parentKey: 'postProduction',
		category: TagCategory.Job,
	},
	{
		name: 'Post Production Supervisor',
		key: 'postProductionSupervisor',
		parentKey: 'postProduction',
		category: TagCategory.Job,
	},
	{
		name: 'Colorist',
		key: 'colorist',
		parentKey: 'postProduction',
		category: TagCategory.Job,
	},
	{
		name: 'Title Designer',
		key: 'titleDesigner',
		parentKey: 'postProduction',
		category: TagCategory.Job,
	},
	{
		name: 'Marketing Executive Publicist',
		key: 'marketingExecutivePublicist',
		parentKey: 'marketingAndDistribution',
		category: TagCategory.Job,
	},
	{
		name: 'Distribution Executive',
		key: 'distributionExecutive',
		parentKey: 'marketingAndDistribution',
		category: TagCategory.Job,
	},
	{
		name: 'Film Archivist',
		key: 'filmArchivist',
		parentKey: 'filmPreservationAndHistory',
		category: TagCategory.Job,
	},
	{
		name: 'Film Historian',
		key: 'filmHistorian',
		parentKey: 'filmPreservationAndHistory',
		category: TagCategory.Job,
	},
	{
		name: 'Film Critic',
		key: 'filmCritic',
		parentKey: 'filmPreservationAndHistory',
		category: TagCategory.Job,
	},

	{
		name: 'Audio Engineer',
		key: 'audioEngineer',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Producer',
		key: 'musicProducer',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Songwriter',
		key: 'songwriter',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Studio Manager',
		key: 'studioManager',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Video Director',
		key: 'musicVideoDirector',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Singer',
		key: 'singerJob',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Backing singer',
		key: 'backingSinger',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Bass guitar',
		key: 'bassGuitar',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Guitarist',
		key: 'guitarist',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Drummer',
		key: 'drummer',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music Teacher/Instructor',
		key: 'musicTeacher',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Composer/Arranger',
		key: 'composer/Arranger',
		parentKey: 'musicIndustryJob',
		category: TagCategory.Job,
	},
	{
		name: 'Personal manager',
		key: 'personalManager',
		parentKey: 'talentAgencyJob',
		category: TagCategory.Job,
	},
	{
		name: 'Talent Agent',
		key: 'talentAgent',
		parentKey: 'talentAgencyJob',
		category: TagCategory.Job,
	},
	{
		name: 'Film publisher',
		key: 'filmPublisher',
		parentKey: 'publishingJob',
		category: TagCategory.Job,
	},
	{
		name: 'Music publisher',
		key: 'musicPublisher',
		parentKey: 'publishingJob',
		category: TagCategory.Job,
	},
	{
		name: 'Game publisher',
		key: 'gamePublisher',
		parentKey: 'publishingJob',
		category: TagCategory.Job,
	},
	{
		name: 'Nft publisher',
		key: 'nftPublisher',
		parentKey: 'publishingJob',
		category: TagCategory.Job,
	},

	{
		name: 'Producer',
		key: 'producer',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Executive',
		key: 'executive',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Producer',
		key: 'producer',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Line Producer',
		key: 'lineProducer',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Co-Producer',
		key: 'coProducer',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Associate Producer',
		key: 'associateProducer',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Unit Production Manager',
		key: 'unitProductionManager',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Production Coordinator',
		key: 'productionCoordinator',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Production Secretary',
		key: 'productionSecretary',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Production Assistant',
		key: 'productionAssistant',
		parentKey: 'productionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Director',
		key: 'director',
		parentKey: 'directionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Assistant Director',
		key: 'assistantDirector',
		parentKey: 'directionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Second Assistant Director',
		key: 'secondAssistantDirector',
		parentKey: 'directionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Screenwriter',
		key: 'screenwriter',
		parentKey: 'writingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Story Editor',
		key: 'storyEditor',
		parentKey: 'writingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Production Designer',
		key: 'productionDesigner',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Art Director',
		key: 'artDirector',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Set Decorator',
		key: 'setDecorator',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Set Designer',
		key: 'setDesigner',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Prop Master',
		key: 'propMaster',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Construction Coordinator',
		key: 'constructionCoordinator',
		parentKey: 'artDepartmentTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Location Manager',
		key: 'locationManager',
		parentKey: 'locationsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Location Scout',
		key: 'locationScout',
		parentKey: 'locationsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Cinematographer/Director of Photography',
		key: 'cDirectorOfPhotography',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Camera Operator',
		key: 'cameraOperator',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Steadicam Operator',
		key: 'steadicamOperator',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Focus Puller/1st Assistant Camera',
		key: 'focusPuller/1stAssistantCamera',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Clapper Loader/2nd Assistant Camera',
		key: 'clapperLoader/2ndAssistantCamera',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Digital Imaging Technician',
		key: 'digitalImagingTechnician',
		parentKey: 'cameraAndCinematographyTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Gaffer',
		key: 'gaffer',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Best Boy Electric',
		key: 'bestBoyElectric',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Electrician',
		key: 'electrician',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Key Grip',
		key: 'keyGrip',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Best Boy Grip',
		key: 'bestBoyGrip',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Grip',
		key: 'grip',
		parentKey: 'lightingAndGripTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Sound Designer',
		key: 'soundDesigner',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Sound Mixer',
		key: 'soundMixer',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Boom Operator',
		key: 'boomOperator',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Foley Artist',
		key: 'foleyArtist',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'ADR Editor',
		key: 'adr',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Dialogue Editor',
		key: 'dialogueEditor',
		parentKey: 'soundTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Composer',
		key: 'composer',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Music Supervisor',
		key: 'musicSupervisor',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Music Editor',
		key: 'musicEditor',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Musician',
		key: 'musician',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Music Arranger',
		key: 'musicArranger',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Music Producer',
		key: 'musicProducer',
		parentKey: 'musicJobTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Casting Director',
		key: 'castingDirector',
		parentKey: 'castingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Talent Agent',
		key: 'talentAgent',
		parentKey: 'castingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Actor',
		key: 'actor',
		parentKey: 'castingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Extras',
		key: 'extras',
		parentKey: 'castingTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Stunt Coordinator',
		key: 'stuntCoordinator',
		parentKey: 'stuntsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Stunt Performer',
		key: 'stuntPerformer',
		parentKey: 'stuntsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Designer',
		key: 'costumeDesigner',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Supervisor',
		key: 'costumeSupervisor',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Costume Assistant',
		key: 'costumeAssistant',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Wardrobe Master',
		key: 'wardrobeMaster',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Makeup Artist',
		key: 'makeupArtist',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Hair Stylist',
		key: 'hairStylist',
		parentKey: 'costumesAndMakeupTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Special Effects Technician',
		key: 'specialEffectsTechnician',
		parentKey: 'specialEffectsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Special Effects Supervisor',
		key: 'specialEffectsSupervisor',
		parentKey: 'specialEffectsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Visual Effects Supervisor',
		key: 'visualEffectsSupervisor',
		parentKey: 'specialEffectsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Visual Effects Artist',
		key: 'visualEffectsArtist',
		parentKey: 'specialEffectsTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Editor',
		key: 'editor',
		parentKey: 'postProductionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Assistant Editor',
		key: 'assistantEditor',
		parentKey: 'postProductionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Post Production Supervisor',
		key: 'postProductionSupervisor',
		parentKey: 'postProductionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Colorist',
		key: 'colorist',
		parentKey: 'postProductionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Title Designer',
		key: 'titleDesigner',
		parentKey: 'postProductionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Marketing Executive Publicist',
		key: 'marketingExecutivePublicist',
		parentKey: 'marketingAndDistributionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Distribution Executive',
		key: 'distributionExecutive',
		parentKey: 'marketingAndDistributionTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Film Archivist',
		key: 'filmArchivist',
		parentKey: 'filmPreservationAndHistoryTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Film Historian',
		key: 'filmHistorian',
		parentKey: 'filmPreservationAndHistoryTelevision',
		category: TagCategory.Job,
	},
	{
		name: 'Film Critic',
		key: 'filmCritic',
		parentKey: 'filmPreservationAndHistoryTelevision',
		category: TagCategory.Job,
	},
];
