export const CERTEFICATES_REPOSITORY = Symbol('CERTEFICATES_REPOSITORY');
export const CERTEFICATES_SERVICES = Symbol('CERTEFICATES_SERVICES');

export const CERTEFICATE_TO_USER_REPOSITORY = Symbol('CERTEFICATE_TO_USER_REPOSITORY');
