export const CHATS_REPOSITORY = Symbol('CHATS_REPOSITORY');
export const CHATS_MEMBERS_REPOSITORY = Symbol('CHATS_MEMBERS_REPOSITORY');
export const CHATS_MESSAGES_REPOSITORY = Symbol('CHATS_MESSAGES_REPOSITORY');

export const CHATS_SERVICE = Symbol('CHATS_SERVICE');
export const CHATS_MEMBERS_SERVICE = Symbol('CHATS_MEMBERS_SERVICE');
export const CHATS_MESSAGES_SERVICE = Symbol('CHATS_MESSAGES_SERVICE');
export const GET_CHATS_LIST_ACTION = Symbol('GET_CHATS_LIST_ACTION');
