export const WALLETS_REPOSITORY = Symbol('WALLETS_REPOSITORY');
export const WALLETS_ACTIONS_REPOSITORY = Symbol('WALLETS_ACTIONS_REPOSITORY');

export const WALLETS_SERVICE = Symbol('WALLETS_SERVICE');
export const WALLETS_ACTIONS_SERVICE = Symbol('WALLETS_ACTIONS_SERVICE');
